spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/v1/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: basket-service
          uri: lb://basket-service
          predicates:
            - Path=/api/v1/baskets/**
        - id: eureka
          uri: http://localhost:8888
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-static
          uri: http://localhost:8888
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/


server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  registerWithEureka: true
  fetchRegistry: true
