spring:
  application:
      name: productservice
  datasource:
    url: jdbc:postgresql://localhost:5432/java3-srs
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/